// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsijaewwfvajvpoapkit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzaWphZXd3ZnZhanZwb2Fwa2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzE5NDQsImV4cCI6MjA2NTE0Nzk0NH0.Z_rIirev6Ohc_R4b29L311GfkXVGtSiuDULk7smRos4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);